### ISSUE TITLE
数据预处理问题

### ISSUE THREAD

**Issue by ckj01** [y8421036/LA-Net#1]
您好，这个数据的预处理是对OCTA-500进行了什么处理？我看OCTA-500官网上面并没有Ground truth这个文件，希望您可以在百忙之中抽出时间回复我

**Comment by y8421036** [comment]
> 您好，这个数据的预处理是对OCTA-500进行了什么处理？我看OCTA-500官网上面并没有Ground truth这个文件，希望您可以在百忙之中抽出时间回复我

你好。该数据集在2020年10月发布了第一版，当时挂在arxiv上的论文题目是“IPN-V2 and OCTA-500: Methodology and Dataset for Retinal Image Segmentation”，标签只有两个前景，即大血管和FAZ，其真值在Ground truth文件夹内。现在最新版题目是“OCTA-500: A Retinal Dataset for Optical Coherence Tomography Angiography Study”，加入了更多前景和label，并把数据集标签文件目录做了修改。
您可以把最新版本中GT_Artery和GT_Vein的前景值取并集然后设为2，并且不要进行旋转操作。这样可以作为Ground truth文件夹来运行程序。另外，如果需要原始Ground truth文件夹也可以与我邮件联系，我通过网盘发给你。

**Comment by ckj01** [comment]
您好，非常感谢您能对我的疑惑做出解答。但是我这里还有一个问题：明明没有对路径的赋值但是仍然会报错说找不到 '/data2/datasets/OCTA-500/3M/OCT'该路径。所以我想问的是，您在编写代码时是否使用了固定赋值，而我没有找到？实在不好意思用这样的问题打扰到您，但是这的确是我目前比较困惑的点，望解答，谢谢！

**Comment by y8421036** [comment]
> 您好，非常感谢您能对我的疑惑做出解答。但是我这里还有一个问题：明明没有对路径的赋值但是仍然会报错说找不到 '/data2/datasets/OCTA-500/3M/OCT'该路径。所以我想问的是，您在编写代码时是否使用了固定赋值，而我没有找到？实在不好意思用这样的问题打扰到您，但是这的确是我目前比较困惑的点，望解答，谢谢！

你好，可以检查一下LA-Net/options/base_options.py文件中的“--dataroot”参数和“modality_filename”参数。前者代表数据集的绝对路径，后者代表要输入的模态和标签。

**Comment by ckj01** [comment]
不好意思，我刚才跑了一下才发现是我服务器配置的问题。但是有一个文件：Label_RV，这个文件我在最新的数据集下载中没有找到，只有一个Label文件，请问他们两个是一个吗？

**Comment by ckj01** [comment]
还有一个就是Features_V2这个文件，请问这个文件是自己生成的吗？这么晚评论很不好意思，但是服务器这边只有晚上才会空闲，实在不好意思，请您见谅

**Comment by y8421036** [comment]
> 不好意思，我刚才跑了一下才发现是我服务器配置的问题。但是有一个文件：Label_RV，这个文件我在最新的数据集下载中没有找到，只有一个Label文件，请问他们两个是一个吗？

Label_RV不是原始数据集的Label文件夹。而是你第一个问题中，由原始的GroundTruth文件夹生成的0、1、2的三分类的标签数据文件夹。具体由LA-Net/data_process/preprocess.py文件生成。

**Comment by y8421036** [comment]
> 还有一个就是Features_V2这个文件，请问这个文件是自己生成的吗？这么晚评论很不好意思，但是服务器这边只有晚上才会空闲，实在不好意思，请您见谅

没事。Features_V2是通过LA-Net/test.py文件生成的。目的是通过LA-Net/train.py文件训练完LA-Net模型后，再通过LA-Net/test.py生成训练LA-Net+模型所需要的中间文件。

**Comment by ckj01** [comment]
好的，另外就是一个刚刚遇到的问题，说是没有Text labels.xlsx，请问这个文件是单独的3M里那个还是总共的从1一直到500的呢？

**Comment by y8421036** [comment]
你好LA-Net的处理和学习过程并没有用到这个xlsx文件。如果还有错误的话，可以把具体的报错文件和具体的报错信息发出来。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月24日(周五) 凌晨0:29
收件人: ***@***.***&gt;;
抄送: "Chaozhi ***@***.******@***.***&gt;;
主题: Re: [y8421036/LA-Net] 数据预处理问题 (Issue #1)




 
好的，另外就是一个刚刚遇到的问题，说是没有Text labels.xlsx，请问这个文件是单独的3M里那个还是总共的从1一直到500的呢？

**Comment by ckj01** [comment]
好的，那可能是我的路径处理错了，但是还有一个比较重要的问题就是，该代码里是否有使用较小显存的设定？我在服务器上跑了一下，4个小时也一直停留在traindata piking...It will take some minute这一步，显存占用也只有288MB，但是服务器是有比较大的空闲的。

**Comment by y8421036** [comment]
这个piking是在把所有的图片文件转换成hdf5格式的文件，为了加速后续读取的速度。这一步还没有开始训练。这一步骤耗时很长，具体时间也取决于cpu的性能。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月24日(周五) 中午1:34
收件人: ***@***.***&gt;;
抄送: "Chaozhi ***@***.******@***.***&gt;;
主题: Re: [y8421036/LA-Net] 数据预处理问题 (Issue #1)




 
好的，那可能是我的路径处理错了，但是还有一个比较重要的问题就是，该代码里是否有使用较小显存的设定？我在服务器上跑了一下，4个小时也一直停留在traindata piking...It will take some minute这一步，显存占用也只有288MB，但是服务器是有比较大的空闲的。

**Comment by y8421036** [comment]
> 好的，那可能是我的路径处理错了，但是还有一个比较重要的问题就是，该代码里是否有使用较小显存的设定？我在服务器上跑了一下，4个小时也一直停留在traindata piking...It will take some minute这一步，显存占用也只有288MB，但是服务器是有比较大的空闲的。

这个piking是在把所有的图片文件转换成hdf5格式的文件，为了加速后续读取的速度。这一步还没有开始训练。这一步骤耗时很长，具体时间也取决于cpu的性能。

**Comment by ckj01** [comment]
您好，代码里面是没有创建该文件的代码吗？我租了一个新的服务器，然后一直就是在报没有traindata.hdf5的错，这个错误感觉是我这边的问题，但是我并有改动代码，只是把logs文件夹改成了root文件夹，而且哪怕创建一个logs文件夹，依然不会创建出来这个文件

**Comment by ckj01** [comment]
您好，他目前显示了这么一个问题：
/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py:952: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv_transpose2d(
Traceback (most recent call last):
  File "/tmp/pycharm_project_850/LA-Net-main/train.py", line 140, in <module>
    train_net(net=net, device=device)
  File "/tmp/pycharm_project_850/LA-Net-main/train.py", line 63, in train_net
    loss.backward()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/_tensor.py", line 525, in backward
    torch.autograd.backward(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [3, 64, 76, 76]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
ERROR conda.cli.main_run:execute(47): `conda run python /tmp/pycharm_project_850/LA-Net-main/train.py` failed. (See above for error)
我问了GPT说是梯度计算出了问题，但是我不知道他说的具体是哪里，我想问一下的是，这是因为我更改了logs文件夹的原因吗

**Comment by ckj01** [comment]
您好，我把梯度计算那里所有的原地操作都改成了非原地操作，然后就跑通了，但是我看了下，logs/best_model2/0.92883/12300.pth这个路径下只有一个0.pth，我不知道是不是我之前对梯度计算的操作导致的

**Comment by ckj01** [comment]
ModuleNotFoundError: No module named 'model_IPN_V2'另外老师我也想问一下，这个报错，我看文件里并没有这个module

**Comment by ckj01** [comment]
> ModuleNotFoundError: No module named 'model_IPN_V2'另外老师我也想问一下，这个报错，我看文件里并没有这个module

您好，这个我已经解决了

**Comment by ckj01** [comment]
> 您好，他目前显示了这么一个问题： /root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py:952: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.) return F.conv_transpose2d( Traceback (most recent call last): File "/tmp/pycharm_project_850/LA-Net-main/train.py", line 140, in train_net(net=net, device=device) File "/tmp/pycharm_project_850/LA-Net-main/train.py", line 63, in train_net loss.backward() File "/root/miniconda3/lib/python3.10/site-packages/torch/_tensor.py", line 525, in backward torch.autograd.backward( File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/**init**.py", line 267, in backward _engine_run_backward( File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward return Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [3, 64, 76, 76]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True). ERROR conda.cli.main_run:execute(47): `conda run python /tmp/pycharm_project_850/LA-Net-main/train.py` failed. (See above for error) 我问了GPT说是梯度计算出了问题，但是我不知道他说的具体是哪里，我想问一下的是，这是因为我更改了logs文件夹的原因吗

现在只有一个这个问题，您的源代码是显示的这个问题，但是我把所有梯度计算的原地操作都改成非原地操作以后，就能够训练了，但是训练的Dice越来越低了，请问这个问题您碰到过吗？

**Comment by ckj01** [comment]
就是每一个Step:1200, Valid_Dice:0.9000601585196926里面的Valid_Dice都越来越高，但是紧接着比如说，1210和1220之类的会越来越低

**Comment by ckj01** [comment]
![QQ截图20240525130332](https://github.com/y8421036/LA-Net/assets/97345936/e538189a-e721-4691-9ce2-07f4bb1ef4a5)
您看，就是这样的情况，开头和结尾的Dice都是走高的，但是中间的就越来越低

**Comment by ckj01** [comment]
> > 您好，他目前显示了这么一个问题： /root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py:952: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.) return F.conv_transpose2d( Traceback (most recent call last): File "/tmp/pycharm_project_850/LA-Net-main/train.py", line 140, in train_net(net=net, device=device) File "/tmp/pycharm_project_850/LA-Net-main/train.py", line 63, in train_net loss.backward() File "/root/miniconda3/lib/python3.10/site-packages/torch/_tensor.py", line 525, in backward torch.autograd.backward( File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/**init**.py", line 267, in backward _engine_run_backward( File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward return Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [3, 64, 76, 76]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True). ERROR conda.cli.main_run:execute(47): `conda run python /tmp/pycharm_project_850/LA-Net-main/train.py` failed. (See above for error) 我问了GPT说是梯度计算出了问题，但是我不知道他说的具体是哪里，我想问一下的是，这是因为我更改了logs文件夹的原因吗
> 
> 现在只有一个这个问题，您的源代码是显示的这个问题，但是我把所有梯度计算的原地操作都改成非原地操作以后，就能够训练了，但是训练的Dice越来越低了，请问这个问题您碰到过吗？

不好意思，那个好像是loss函数慢慢变低了，打扰了，头昏了

**Comment by y8421036** [comment]
> ![QQ截图20240525130332](https://private-user-images.githubusercontent.com/97345936/333773485-e538189a-e721-4691-9ce2-07f4bb1ef4a5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MTcwNzcsIm5iZiI6MTcxNjYxNjc3NywicGF0aCI6Ii85NzM0NTkzNi8zMzM3NzM0ODUtZTUzODE4OWEtZTcyMS00NjkxLTljZTItMDdmNGJiMWVmNGE1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA1NTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3Yjk0ZTBmM2QwYmQwOGUyOGQ3ZjlmNjZhYjc1MmNkNDI1MTJhNDljNmY2ZTYzMjk1OTBkOTVmMmQyYzg3YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6HeWXUQrXPu38Wvi3F6PIGbVRvt0TFOgu1vArf4rdyg) 您看，就是这样的情况，开头和结尾的Dice都是走高的，但是中间的就越来越低

Valid_dice的输出是验证集dice值，其他的没有valid的输出都是loss的值。
