### ISSUE TITLE
train模型跑完，使用test测试以后应该直接跑train+吗？

### ISSUE THREAD

**Issue by ckj01** [y8421036/LA-Net#2]
请问该模型大概的一个流程是什么样子的？我想看看自己的流程对不对

**Comment by y8421036** [comment]
> 请问该模型大概的一个流程是什么样子的？我想看看自己的流程对不对

train.py运行后，会先打印当前网络implement的所有参数，然后开始输出训练阶段每次迭代的loss，然后每300次迭代输出一次验证集的dice。训练结束后，在logs/best_model文件夹保存了当前top3的结果。

**Comment by ckj01** [comment]
哦哦，那这个就是最后的的分割了吗？最后只需要用test测试一下，然后npy=1，2，3，4保存结果就结束了吗？

**Comment by y8421036** [comment]
> 哦哦，那这个就是最后的的分割了吗？最后只需要用test测试一下，然后npy=1，2，3，4保存结果就结束了吗？

LA-Net的最后结果可以通过test.py的npy=2得到。npy=1生成训练完的LA-Net的中间特征，用于训练LA-Net+。

**Comment by ckj01** [comment]
所以您的意思是，如果我要得到完整的LA-Net在OCTA-500数据集上的表现，要分别使用3M和6M数据各train一遍并且test一遍是吗？

**Comment by y8421036** [comment]
> 所以您的意思是，如果我要得到完整的LA-Net在OCTA-500数据集上的表现，要分别使用3M和6M数据各train一遍并且test一遍是吗？

OCTA-500有两个不同视域大小的子集，互不影响。可以只跑一个看模型能力。train.py和test.py后只是LA-Net模型的结果，本文最终结果以LA-Net+为主，如果完整复现，则需要train+.py和test+.py也都跑完，才能得到LA-Net+模型的结果。

**Comment by ckj01** [comment]
嗷嗷，好的，但是我跑完以后，Features_V2文件里缺少201到300的，请问这是在代码里设计好的吗？

**Comment by ckj01** [comment]
> 嗷嗷，好的，但是我跑完以后，Features_V2文件里缺少201到300的，请问这是在代码里设计好的吗？

不好意思，我找到了，我以为是设计成弹性的，文件多大就用多大的

**Comment by ckj01** [comment]
您好，还有一个问题就是，那个test+文件是测试其他模型的吗？

**Comment by y8421036** [comment]
> 您好，还有一个问题就是，那个test+文件是测试其他模型的吗？

本文有两个模型，一个是LA-Net，另一个是LA-Net+。test+.py用于测试训练完的LA-Net+模型。

**Comment by ckj01** [comment]
您好，还有最后一个我比较关心的问题，该项目是使用得OCT和OCTA两种输入模态是吗？那这两个模型最后的处理结果可以说成是两种模态融合的模型吗？望解答。
